### ISSUE TITLE
get exception when Push to Remote

### ISSUE THREAD

**Issue by supergahar** [geluk/pass-winmenu#75]
Hi every time i tried to "Push to Remote" always get this exception. im using auto git. When im using "Open Shell" use git commit then git push, it works just fine.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PassWinmenu.ExternalPrograms.Git.CommitFile(String filePath)
   at PassWinmenu.Windows.DialogCreator.AddPassword()
   at PassWinmenu.WinApi.Notifications.<>c__DisplayClass11_0.<AddMenuActions>b__1(Object sender, EventArgs args)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by tonitch** [comment]
I do have the same issue, I tried to modify config for git native but no changes

**Comment by geluk** [comment]
Thanks for your report, and my apologies for responding so late.
I haven't been able to discover the underlying cause yet, but I created a new build which should at least prevent the application from crashing if the same condition occurs. Instead, it will report an error in this case.
You can download the new version here: https://ci.appveyor.com/api/buildjobs/rar2agcxh6jc8y1v/artifacts/pass-winmenu%2Fbin%2FRelease%2Fpass-winmenu.exe

Could you please test it again with this build? If you get an error again, please report the error message and the logs (right click the notification area icon -> `More actions` -> `View logs`). Thanks!

**Comment by supergahar** [comment]
i just tried it... its worked. thanks!

**Comment by FranekStark** [comment]
#73

**Comment by geluk** [comment]
I've just published [v1.11.1](https://github.com/geluk/pass-winmenu/releases/tag/v1.11.1), which fixes this issue.

I'll close the issue now, but if the problem persists, feel free to open a new issue, or to reopen this one.
