### ISSUE TITLE
Exceptions when pushing and pulling via GUI (GIT_SSH added multiple times to dictionary?)

### ISSUE THREAD

**Issue by saggitar** [geluk/pass-winmenu#98]
Since using the latest build I get an unhandled Exception when pushing and pulling using the GUI (Shell works fine):

```
System.ArgumentException: Item has already been added. Key in dictionary: 'GIT_SSH'  Key being added: 'GIT_SSH'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at PassWinmenu.ExternalPrograms.NativeGitSyncStrategy.CallGit(String arguments)
   at PassWinmenu.Actions.RetrieveChangesAction.Execute()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

When using pull I get a detailed Debug Info Popup from .NET (see above). When pushing, the same error happens but I only get a pass-winmenu popup and the log file showing the same error:

```
[19:47:21.934] ArgumentException (Item has already been added. Key in dictionary: 'GIT_SSH'  Key being added: 'GIT_SSH') in :0:0
[19:47:21.934]   -> in System.Collections.Hashtable.Insert -- :0:0
[19:47:21.934]   -> in PassWinmenu.ExternalPrograms.NativeGitSyncStrategy.CallGit -- :0:0
[19:47:21.934]   -> in PassWinmenu.Actions.CommitChangesAction.Execute -- :0:0
```

I am using "fresh" default config, except for `native-git` mode and using `plink` as SSH agent.

I was looking at open issues,  but the error persists if using the patched executable from [https://github.com/geluk/pass-winmenu/issues/97](https://github.com/geluk/pass-winmenu/issues/97#issuecomment-917083590)

**Comment by geluk** [comment]
Thanks for your report! It looks like you have already set the `GIT_SSH` environment variable somewhere If you additionally have the 'git.ssh-path` configuration variable set, pass-winmenu tries to set the variable as well, which leads to the error you're seeing.

Setting `git.ssh-path` to `null` (or removing the `GIT_SSH` environment variable) will allow you to work around the issue for the time being.

To fix the error, I think it's appropriate for pass-winmenu to allow the value of `git.ssh-path` to override the environment variable when calling git. I've created a new build that does this correctly, could you check if it resolves your issue?

You can download the build here: https://ci.appveyor.com/api/buildjobs/o8um4pvb5hxvpwa2/artifacts/pass-winmenu%2Fbin%2FRelease%2Fpass-winmenu.exe

**Comment by saggitar** [comment]
That makes sense :)
Resolved with the new build!
